_base_:
  - cfgs/env/cluster.yaml

trainer: hip_latent_extract_trainer

datasets:
  train:
    name: wrapper_coord_value
    args:
      dataset:
        name: era5_temperature
        args:
          split: train
          root_path: /scratch/htc/aurbano/datasets/era5
          n_inp: 4140
          n_query: 4140
          to_pm1: true
    loader:
      batch_size: 256
      num_workers: 8

  val:
    name: wrapper_coord_value
    args:
      dataset:
        name: era5_temperature
        args:
          split: val
          root_path: /scratch/htc/aurbano/datasets/era5
          n_inp: 4140
          n_query: 4140
          to_pm1: true
    loader:
      batch_size: 256
      num_workers: 8

  test:
    name: wrapper_coord_value
    args:
      dataset:
        name: era5_temperature
        args:
          split: test
          root_path: /scratch/htc/aurbano/datasets/era5
          n_inp: 4140
          n_query: 4140
          to_pm1: true
    loader:
      batch_size: 256
      num_workers: 8

extract:
  stage1_ckpt: /ABS/PATH/TO/STAGE1/best-model.pth

  out_root: from_stage1_ckpt
  out_subdir: extract/latents_era5_tc
  stats_mode: token_channel

  splits: [train, val, test]
  block: last

  shard_size: 2048

  batch_size: 256
  num_workers: 8

  save_dtype: float32
  use_amp: false
